app/blueprints/admin.py
from ..util.myRequest import MyRequest
import json
from flask import Flask , request, session , render_template , Blueprint, redirect , url_for

admin_blueprint = Blueprint('admin', __name__)

@admin_blueprint.route("/admin", methods=["GET"])
def index():
    if session.get('logged_user') is None: 
        return redirect(url_for('auth.index'))
    else:
        
        userList = json.loads('[]') 
        user = json.loads(session['logged_user'])
        if user['admin'] == False :
            return redirect(url_for('auth.index'))
        else:
            res = MyRequest.get('/v1/users')
            if res.status_code == 200:
                userList = res.json()['data']
    
    return render_template('admin.html' , user=user,  userList=userList )

@admin_blueprint.route("/admin/find", methods=["POST"])
def find():
    info = request.form

    if info.get('mybookemark-user', None) is None:
        return redirect(url_for('admin.index',error="Selecione um usuário"))
    else:
        res = MyRequest.get('/v1/users')
        if res.status_code == 200:
            userList = res.json()['data']
        else:
            userList = json.loads('[]')

        res = MyRequest.get('/v1/users/'+info.get('mybookemark-user',None))
        if res.status_code == 200:
            userSelected = res.json()

        user = json.loads(session['logged_user'])
        res = MyRequest.get('/v1/users/'+info.get('mybookemark-user',None)+'/bookmarks')
        if res.status_code == 200:
            bookmarkList = res.json()['data']
        else:
            bookmarkList = json.loads('[]')
        
    return render_template('admin.html' , user=user, userSelected=userSelected , userList=userList , bookmarkList=bookmarkList )
        

app/blueprints/auth.py
from ..util.myRequest import MyRequest
import json
from flask import Flask , request, session , render_template , Blueprint, redirect , url_for

auth_blueprint = Blueprint('auth', __name__)

@auth_blueprint.route("/", methods=["GET"])
def index():
    if session.get('logged_user') is None:
        return redirect(url_for('auth.login')) 

    user = json.loads(session['logged_user'])

    # listando os bookmarks do usuário
    #res = requests.get('http://api:3000/api/v1/users/'+user['_id']+'/bookmarks')

    res = MyRequest.get('/v1/users/'+user['_id']+'/bookmarks')
    if res.status_code == 200:
        bookmarkList = res.json()['data']
    else:
        bookmarkList = json.loads('[]')

    return render_template('home.html' , user=user , bookmarkList=bookmarkList )

@auth_blueprint.route("/login", methods=["GET"])
def login():
    message = request.args.get('m')
    return render_template('sign.html', message=message)


@auth_blueprint.route("/sign/in", methods=["GET", "POST"])
def signIn():
    if request.method == "GET":
        return redirect(url_for('.index'))

    info = request.form
    user = {
        'email':info['user-email'],
        'password':info['user-password']
    }

    #res = requests.post('http://api:3000/api/sign/in', data=user)    

    res = MyRequest.post('/sign/in', user)
    
    if res.status_code == 200:
        loggedUser = res.json()['data']
        if loggedUser['token'] is not None:
            session['logged_user'] = json.dumps(loggedUser)
            return redirect(url_for('.index'))
    else:
        info = res.json()['message']
    
    return render_template('sign.html', signInError=info)

@auth_blueprint.route("/sign/up", methods=["GET", "POST"])
def signUp():
    if request.method == "GET":
        return redirect(url_for('.index'))  

    info = request.form
    admin = 'false'
    if info.get('user-admin', None) is not None:
        admin = info['user-admin']
        
    user = {
        'name':info['user-name'],
        'email':info['user-email'],
        'password':info['user-password'],
        'admin':admin
    }
    #res = requests.post('http://api:3000/api/sign/up', data=user)
    
    res = MyRequest.post('/sign/up',user)
    
    if res.status_code == 201:
        loggedUser = res.json()['data']
        if loggedUser['token'] is not None:
            session['logged_user'] = json.dumps(loggedUser)
            return redirect(url_for('.index'))
    else:
        info = res.json()['message']

    return render_template('sign.html', signUpError=info)


@auth_blueprint.route("/sign/out", methods=["GET", "POST"])
def signOut():
    session.clear()
    return redirect(url_for('.index'))

app/blueprints/bookmark.py
import json
from flask import Flask , flash, request, session , render_template , Blueprint, redirect , url_for
from ..util.myRequest import MyRequest

bookmark_blueprint = Blueprint('bookmark', __name__)

@bookmark_blueprint.route("/bookmark/create", methods=["GET","POST"])
def create():
    if request.method == "GET":
        return redirect(url_for('auth.index'))

    info = request.form

    bookmark = {
        'owner':info['bookmark-owner'],
        'name':info['bookmark-name'],
        'url':info['bookmark-url']
    }
    res = MyRequest.post('/v1/bookmarks', bookmark)

    if res.status_code != 201:
        error = res.json()['message']
        flash(error,'error')
        return redirect(url_for('auth.index')) 

    return redirect(url_for('auth.index')) 
    
@bookmark_blueprint.route("/bookmark/delete/<id>", methods=["GET","POST"])
def delete(id):

    res = MyRequest.delete('/v1/bookmarks/'+id)

    if res.status_code != 200:
        error = res.json()['message']
        flash(error,'error')
        return redirect(url_for('auth.index')) 

    return redirect(url_for('auth.index'))

@bookmark_blueprint.route("/bookmark/edit/<id>", methods=["GET","POST"])
def edit(id):
    
    if request.method == "GET":
        return redirect(url_for('auth.index'))
    
    info = request.form
    bookmark = {
        'owner':info['bookmark-owner'],
        'name':info['bookmark-name'],
        'url':info['bookmark-url']
    }

    res = MyRequest.put('/v1/bookmarks/'+id , bookmark)
    
    if res.status_code != 200:
        error = res.json()['message']
        flash(error,'error')
        return redirect(url_for('auth.index')) 

    return redirect(url_for('auth.index'))
    

app/main.py
from flask import Flask , render_template, Session
from .blueprints.admin import admin_blueprint
from .blueprints.auth import auth_blueprint
from .blueprints.bookmark  import bookmark_blueprint

app = Flask(__name__)
sess = Session()
app.secret_key = 'emequatrou'
app.config['SESSION_TYPE'] = 'filesystem'

@app.errorhandler(401)
def page_not_found(e):
    return render_template('401.html'), 401

@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

@app.errorhandler(500)
def page_not_found(e):
    return render_template('500.html'), 500

app.register_blueprint(admin_blueprint)
app.register_blueprint(auth_blueprint)
app.register_blueprint(bookmark_blueprint)
 

if __name__ == "__main__":
    
    sess.init_app(app)

    # Only for debugging while developing
    app.run(host='0.0.0.0', debug=True, port=80)

app/templates/401.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <h1 class="primary-color upper"><i class="glyphicon glyphicon-bookmark"></i> My Bookmarks</h1>
    </div>
    <div class="middle-box text-center animated fadeInDown">
        <h2 class="textiary-color upper">Acesso negado</h2>
        <h1 class="primary-color upper">401</h1>
        <div class="error-desc">
            Hum... <br>
            Parece que você não tem acesso a esse conteúdo.
            Tente se logar novamente ou fale com um dos administradores.
        </div>
        <a  class="btn  primary-color-bkg" href="{{url_for('auth.login')}}" class="btn btn-primary">Ir para Login</a>
    </div>
</div>

{% endblock %}

app/templates/admin.html
{% extends "layout.html" %}
{% block content %}

    <div class="container-fluid header">
        <header>
            <div class="col-xs-12 col-md-6">
                <h1 class="primary-color upper"><i class="glyphicon glyphicon-bookmark"></i> My Bookmarks</h1>
            </div>
            <div class="col-xs-12 col-md-6 tertiary-color">
                    <nav class="nav-top-links text-right">
                        <div class="user-logged"><i class="glyphicon glyphicon-user"></i> {{user.name}}</div>
                        <a class="admin" href="{{url_for('auth.index')}}"> <i class="glyphicon glyphicon-bookmark"></i> Minha Área</a>
                        <a class="" href="{{url_for('auth.signOut')}}"><i class="glyphicon glyphicon-log-out"></i> Sair</a>
                    </nav>
            </div>
        </header> 
    </div>

    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-xs-12">
                        <h4 class="tertiary-color upper"><i class="glyphicon glyphicon-bookmark"></i> Filtrar bookmarks por usuário </h4>
                    </div>
                    <form role="form" class="form" action="{{url_for('admin.find')}}" method="post" >
                        <div class="col-xs-12 col-md-6 vertical-space">
                            <select name="mybookemark-user" id="mybookemark-user" class="form-control">
                                <option value="">Escolha um usuário </option>
                                {% for u in userList %}
                                <option value="{{u._id}}">{{u.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-xs-12 col-md-2 vertical-space ">
                            <button type="submit" class="btn primary-color-bkg btn-block">Buscar</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
        {% if userSelected is defined %}
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul class="col-xs-12 list bookmar-list" id="accordion" role="tablist" aria-multiselectable="true">
                        {% for bookmark in bookmarkList %}
                        <li class="col-xs-12 bookmark-item">
                            <div class="" role="tab" id="item-{{bookmark._id}}">
                                <div class="col-xs-12 col-md-8 bookmark-item-title upper tertiary-color"><a class="tertiary-color" href="{{bookmark.url}}" target="_blank" ><i class="glyphicon glyphicon-link"></i> {{bookmark.name or bookmark.url }}</a></div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    {% if bookmarkList|length == 0 %}
                    <h2 class="text-center tertiary-color">{{userSelected.name}} ainda não cadastrou nenhum bookmark</h2>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>   
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}
{% block content %}

    <div class="container-fluid header">
        <header>
            <div class="col-xs-12 col-md-6">
                <h1 class="primary-color upper"><i class="glyphicon glyphicon-bookmark"></i> My Bookmarks</h1>
            </div>
            <div class="col-xs-12 col-md-6 tertiary-color">
                    <nav class="nav-top-links text-right">
                        <div class="user-logged"><i class="glyphicon glyphicon-user"></i> {{user.name}}</div>
                        {% if user.admin == true %}
                        <a class="admin" href="{{url_for('admin.index')}}" > <i class="glyphicon glyphicon-lock"></i> Area Administrativa</a>
                        {% endif %}
                        <a class="" href="{{url_for('auth.signOut')}}"><i class="glyphicon glyphicon-log-out"></i> Sair</a>
                    </nav>
            </div>
        </header> 
    </div>

    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-xs-12">
                            <h4 class="tertiary-color upper"><i class="glyphicon glyphicon-bookmark"></i> Novo bookmark</h4>
                    </div>
                    <form role="form" class="form" action="{{url_for('bookmark.create')}}" method="post" >
                        <input type="hidden" name="bookmark-owner" value="{{user._id}}">
                            
                        <div class="col-xs-12 col-md-6 vertical-space">
                            <input type="text" name="bookmark-name" class="form-control" placeholder="Digite uma nome para o bookmark">
                        </div>
                        <div class="col-xs-12 col-md-6 vertical-space">
                                <input type="text" name="bookmark-url" class="form-control" placeholder="http://minhaurlfavorita.com.br">
                        </div>
                        <div class="col-md-2 vertical-space ">
                            <button type="submit" class="btn primary-color-bkg btn-block">Cadastrar</button>
                        </div>
                    </form>
                    {% with errors = get_flashed_messages(category_filter=["error"]) %}
                    {% if errors %}
                    <div class="col-xs-12 text-danger">
                        {%- for msg in errors %}
                        <div class="text-right">{{ msg }}</div>
                        {% endfor -%}
                    </div>
                    {% endif %}
                    {% endwith %}
                </div>
            </div>

        </div>
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul class="col-xs-12 list bookmar-list" id="accordion" role="tablist" aria-multiselectable="true">
                        {% for bookmark in bookmarkList %}
                        <li class="col-xs-12 bookmark-item">
                            <div class="" role="tab" id="item-{{bookmark._id}}">
                                <div class="col-xs-12 col-md-8 bookmark-item-title upper tertiary-color"><a class="tertiary-color" href="{{bookmark.url}}" target="_blank" ><i class="glyphicon glyphicon-link"></i> {{bookmark.name or bookmark.url}}</a></div>
                                <div class="col-xs-12 col-md-4 bookmark-item-actions text-right">
                                    <span class="action-item"><a class="primary-color" role="button" data-toggle="collapse" data-parent="#accordion" href="#acordion-{{bookmark._id}}" aria-expanded="true" aria-controls="acordion-{{bookmark._id}}"><i class="glyphicon glyphicon-pencil"></i></a></span>
                                    <span class="action-item"><a class="text-danger" href="{{url_for('bookmark.delete', id=bookmark._id)}}"><i class="glyphicon glyphicon-trash"></i></a></span>
                                </div>
                            </div>
                            <div id="acordion-{{bookmark._id}}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="item-{{bookmark._id}}">
                                <div class="">
                                    <form role="form" class="form" action="{{url_for('bookmark.edit', id=bookmark._id)}}" method="post" >
                                        <input type="hidden" name="bookmark-owner" value="{{bookmark.owner}}">
                                            
                                        <div class="col-xs-12 col-md-6 vertical-space">
                                            <input type="text" name="bookmark-name" class="form-control" placeholder="Digite uma nome para o bookmark" value="{{bookmark.name}}">
                                        </div>
                                        <div class="col-xs-12 col-md-6 vertical-space">
                                                <input type="text" name="bookmark-url" class="form-control" placeholder="http://minhaurlfavorita.com.br" value="{{bookmark.url}}">
                                        </div>
                                        <div class="col-md-2 vertical-space ">
                                            <button type="submit" class="btn primary-color-bkg btn-block">Salvar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    {% if bookmarkList|length == 0 %}
                    <h2 class="text-center tertiary-color">Não perca mais tempo, cadastre já seu primeiro bookmark acima <i class="glyphicon glyphicon-hand-up"></i></h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    
  
    
        
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bookmarks App - M4U</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
        {% block content %}
        {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script>
      //todo: criar diretorio de scripts
        $(document).ready(function(){
            $('.edit-item').click(function(){
                console.log("editar")
                $("#modal").modal('show')
            })
        })
    </script>
  
  </body>
</html>

app/templates/sign.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <h1 class="primary-color upper"><i class="glyphicon glyphicon-bookmark"></i> My Bookmarks</h1>
        <h3 class="tertiary-color upper" >Gerenciar suas URLS favoritas nunca foi tão fácil</h3>
    </div>
    <div class="row register">
            <div class="middle-box">
                <div class="form-box">
                    <div class="form-top">
                        <div class="form-top-right">
                            <i class="fa fa-lock"></i>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <form role="form" action="{{url_for('auth.signIn')}}" method="post" class="login-form">
                            <div class="form-group">
                                <label class="sr-only" for="user-email">Email</label>
                                <input type="email" name="user-email" placeholder="Digite seu email" class="user-email form-control" id="user-email">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="user-password">Senha</label>
                                <input type="password" name="user-password" placeholder="Digite sua senha" class="user-password form-control" id="user-password">
                            </div>
                            {% if signInError is defined %}
                                <div class="alert alert-danger text-center">
                                    {{ signInError }}
                                </div>
                            {% endif %}
                            <button type="submit" class="btn btn-block primary-color-bkg ">Logar</button>
                        </form>
                    </div>
                </div>
                <div class="text-center tertiary-color label-register">ainda não tem cadastro?</div>
                <div class="form-box ">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h4 class="text-center upper">Cadastre-se</h4>
                            <div class="text-center tertiary-color">Comece agora mesmo a salvar suas URL do <i class="primary-color glyphicon glyphicon-heart"></i></div>

                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-pencil"></i>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <form role="form" action="{{url_for('auth.signUp')}}" method="post" class="registration-form">
                            <div class="form-group">
                                <label class="sr-only" for="user-name">Nome</label>
                                <input type="text" name="user-name" placeholder="Digite seu nome " class="user-name form-control" id="user-name">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="user-email">Email</label>
                                <input type="email" name="user-email" placeholder="Digite seu email" class="user-email form-control" id="user-email">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="user-password">Senha</label>
                                <input type="password" name="user-password" placeholder="Digite uma senha" class="user-password form-control" id="user-password">
                            </div>
                            <div class="form-group">
                                <label class=" tertiary-color" for="user-admin">Deseja ser um Administrador?</label>
                                <input type="checkbox" name="user-admin" class="" value="true" id="user-admin" />
                            </div>
                            {% if signUpError is defined  %}
                            <div class="alert alert-danger text-center">
                                {{ signUpError }}
                            </div>
                            {% endif %}
                            <button type="submit" class="btn btn-block primary-color-bkg">Cadastrar</button>
                        </form>
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}